// <auto-generated />
using System;
using IMC.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace IMC.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(IMCDbContext))]
    partial class IMCDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("IMC.Domain.Paint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Column")
                        .HasColumnType("integer");

                    b.Property<int>("Row")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(250)
                        .HasColumnType("character varying(250)");

                    b.Property<string>("Type")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Id")
                        .IsUnique();

                    b.ToTable("Paints");

                    b.HasData(
                        new
                        {
                            Id = new Guid("b5400f35-e664-4c09-b4e5-ba7365282588"),
                            Color = "#63b521",
                            Column = 1,
                            Row = 1,
                            Title = "Warboss Green",
                            Type = "Layer"
                        },
                        new
                        {
                            Id = new Guid("1c8d768e-4c33-49b2-a136-a49e80bfe372"),
                            Color = "#000000",
                            Column = 1,
                            Row = 2,
                            Title = "Nuln Oil",
                            Type = "Shade"
                        },
                        new
                        {
                            Id = new Guid("4418106b-2a7a-4bbd-a6b7-0dc962e56467"),
                            Color = "#33312D",
                            Column = 1,
                            Row = 3,
                            Title = "Dryad Bark",
                            Type = "Base"
                        },
                        new
                        {
                            Id = new Guid("3f168c6c-b670-4628-bdd2-a87417b6934b"),
                            Color = "#f0f1ce",
                            Column = 1,
                            Row = 4,
                            Title = "Screaming Skull",
                            Type = "Layer"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
